# Generated by Django 3.1.4 on 2020-12-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('plant_id', models.IntegerField(max_length=200)),
                ('price', models.CharField(max_length=200)),
            ],
        ),
    ]
