# Generated by Django 3.1.4 on 2020-12-30 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0002_auto_20201230_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstpage.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='plants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstpage.plants'),
        ),
    ]
