# Generated by Django 3.1.4 on 2020-12-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0004_auto_20201230_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.AddField(
            model_name='plants',
            name='category',
            field=models.CharField(choices=[('Flower', 'Flower'), ('Fruits', 'Fruits'), ('Vegetables', 'Vegetables')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plants',
            name='tags',
            field=models.ManyToManyField(to='firstpage.Tag'),
        ),
    ]
