# Generated by Django 3.1.4 on 2020-12-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0009_auto_20201231_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='image',
            field=models.ImageField(default='rose.jpg', upload_to='plants/'),
        ),
    ]
