# Generated by Django 3.1.4 on 2020-12-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0011_auto_20201231_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='image',
            field=models.ImageField(blank=True, default='rose.jpg', null=True, upload_to=''),
        ),
    ]
