# Generated by Django 3.1.4 on 2020-12-31 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0012_auto_20201231_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
