# Generated by Django 3.1.4 on 2020-12-31 09:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0014_auto_20201231_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstpage.customer')),
                ('plants', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstpage.plants')),
            ],
        ),
    ]
