# Generated by Django 3.1.4 on 2020-12-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0017_cartorders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
