# Generated by Django 3.1.4 on 2020-12-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0020_auto_20201231_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
